finished 04-02-skeleton
js-tasks-ru/htmlcss-20220616_vs32 pull request #6
Opened 2022-07-02 12:35 UTC by VS322

2022-07-02 12:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-04 14:06 UTC, GSemikozov requested changes

2022-07-04 14:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                <div class="skeleton__item_circle"></div>
модификатор в отрыве от того что модифицируем? скорее все-таки это просто элемент - skeleton__circle

2022-07-04 14:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                <div class="skeleton__item_upper">
"skeleton__upper

2022-07-04 14:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                    <div class="skeleton__item skeleton__item_upper" style="width: 45%"></div>
skeleton__item skeleton__item_long и так далее, инлайнить ширину здесь не надо, это можно оформить за счет модификаторов

2022-07-10 09:16 UTC, GSemikozov approved these changes

2022-07-10 09:16 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-07-10 09:25 UTC, GSemikozov approved these changes

2022-07-10 09:25 UTC, merged