finished dz 05-03-calendar
js-tasks-ru/htmlcss-20220616_vs32 pull request #8
Opened 2022-07-07 17:22 UTC by VS322

2022-07-07 17:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-10 09:18 UTC, GSemikozov requested changes

2022-07-10 09:18 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +            <div class="calendar__tittle"></div>
почему-то пустой тайтл) + если это заголовок - лучше использовать семантический тег

2022-07-10 09:18 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    max-width: 252px;
по дизайну вроде другие цифры

2022-07-11 16:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-12 10:18 UTC, merged